services:
  suricata:
    build:
      context: ./services
      dockerfile: ./suricata/Dockerfile
    container_name: suricata
    privileged: true
    cap_add: 
      - NET_ADMIN
      - SYS_NICE
    network_mode: host  # Nécessaire pour capturer le trafic réseau
    volumes:
      - /var/log/suricata:/var/log/suricata:rw  # Logs Suricata
      - /var/log/suricata:/home/suricata  # Réplication des logs
      - ./services/suricata/dataset:/home/dataset  # Dataset pour analyse
      - ./services/suricata/config/docker-entrypoint.sh:/docker-entrypoint.sh  # Script d'initialisation
      - ./suricata/etc:/etc/suricata  # Configuration personnalisée
      - ./suricata/rules:/var/lib/suricata/rules  # Règles personnalisées
    environment:
      - TZ=Europe/Paris
      - SURICATA_OPTIONS=-i ${INTERFACE} --set vars.address-groups.HOME_NET=${HOME_NET}
      - PGID=${GID:-1000}
      - PUID=${UID:-1000}
      - SURICATA_INTERFACE=${INTERFACE}
      - SURICATA_HOME_NET=${HOME_NET}
      - COMMUNITY_ID=${COMMUNITY_ID}
    command: -i ${INTERFACE:-eth0}  # Interface réseau à surveiller
    restart: unless-stopped

networks:
  soc_network:
    driver: bridge
