
name: Deploy Services
on: workflow_call
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [elk, opencti, openbas]
    steps:
      - name: Initialize Docker Swarm
        run: docker swarm init || echo "Already initialized"
      - name: Restore workspace and env
        uses: actions/download-artifact@v4
        with:
          name: env_${{ matrix.service }}
      - name: Deploy with Docker Swarm
        run: docker stack deploy -c ${{ matrix.service }}/docker-compose.yml ${{ matrix.service }}
