
name: Main CI Orchestrator
on: [push, pull_request]
jobs:
  services:
    runs-on: ubuntu-latest
    outputs:
      list: ${{ steps.set-services.outputs.list }}
    steps:
      - id: set-services
        run: echo "::set-output name=list::[\"elk\", \"opencti\", \"openbas\"]"
  setup:
    needs: services
    uses: ./.github/workflows/setup.yml
  build:
    needs: setup
    uses: ./.github/workflows/build.yml
  tests:
    needs: build
    uses: ./.github/workflows/tests.yml
  deploy:
    needs: tests
    uses: ./.github/workflows/deploy.yml
  check:
    needs: deploy
    uses: ./.github/workflows/check.yml
  logs:
    needs: check
    uses: ./.github/workflows/logs.yml
  security:
    uses: ./.github/workflows/security.yml
  docker_lint:
    uses: ./.github/workflows/docker-lint.yml
  pr_management:
    needs: logs
    uses: ./.github/workflows/pr-branches.yml
